language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer install --prefer-source
script:
  - vendor/bin/phpspec run -v
addons:
    code_climate:
        repo_token: 94aa8e304bbd9d5485ff6a6658070477c35928fc180ab05c740fe71036394bd7
notifications:
  slack: samiul:6a9KzXbsycCdfzz2UAno7UTC
  
